declare module 'react-native-ico-pixel' {
    import { ReactNode } from 'react';
    import { SvgProps, AdditionalProps } from 'react-native-svg';

    type iconNames = 'account-box' |
      'account' |
      'alert-box-fill' |
      'alert-box' |
      'alert-circle-fill' |
      'alert-circle' |
      'alert-rhombus-fill' |
      'alert-rhombus' |
      'alert' |
      'alpha-a-fill' |
      'alpha-a' |
      'alpha-b-fill' |
      'alpha-b' |
      'alpha-c-fill' |
      'alpha-c' |
      'alpha-d-fill' |
      'alpha-d' |
      'alpha-e-fill' |
      'alpha-e' |
      'alpha-f-fill' |
      'alpha-f' |
      'alpha-g-fill' |
      'alpha-g' |
      'alpha-h-fill' |
      'alpha-h' |
      'alpha-i-fill' |
      'alpha-i' |
      'alpha-j-fill' |
      'alpha-j' |
      'alpha-k-fill' |
      'alpha-k' |
      'alpha-l-fill' |
      'alpha-l' |
      'alpha-m-fill' |
      'alpha-m' |
      'alpha-n-fill' |
      'alpha-n' |
      'alpha-o-fill' |
      'alpha-o' |
      'alpha-p-fill' |
      'alpha-p' |
      'alpha-q-fill' |
      'alpha-q' |
      'alpha-r-fill' |
      'alpha-r' |
      'alpha-s-fill' |
      'alpha-s' |
      'alpha-t-fill' |
      'alpha-t' |
      'alpha-u-fill' |
      'alpha-u' |
      'alpha-v-fill' |
      'alpha-v' |
      'alpha-w-fill' |
      'alpha-w' |
      'alpha-x-fill' |
      'alpha-x' |
      'alpha-y-fill' |
      'alpha-y' |
      'alpha-z-fill' |
      'alpha-z' |
      'application-code' |
      'application' |
      'archive' |
      'arrow-bottom-left-circle' |
      'arrow-bottom-left' |
      'arrow-bottom-right-circle' |
      'arrow-bottom-right' |
      'arrow-down-bold' |
      'arrow-down-circle' |
      'arrow-down-left' |
      'arrow-down-right' |
      'arrow-down' |
      'arrow-left-bold' |
      'arrow-left-circle' |
      'arrow-left-down' |
      'arrow-left-right' |
      'arrow-left-up' |
      'arrow-left' |
      'arrow-right-bold' |
      'arrow-right-circle' |
      'arrow-right-down' |
      'arrow-right-up' |
      'arrow-right' |
      'arrow-top-left-circle' |
      'arrow-top-left' |
      'arrow-top-right-circle' |
      'arrow-top-right' |
      'arrow-up-bold' |
      'arrow-up-circle' |
      'arrow-up-down' |
      'arrow-up-left' |
      'arrow-up-right' |
      'arrow-up' |
      'arrow' |
      'axe' |
      'bag-personal-fill' |
      'bag-personal' |
      'battery-0' |
      'battery-100' |
      'battery-25' |
      'battery-50' |
      'battery-75' |
      'battle-axe' |
      'book' |
      'bookmark' |
      'border-bottom-left-right' |
      'border-bottom-left' |
      'border-bottom-right' |
      'border-bottom' |
      'border-inside' |
      'border-left-right' |
      'border-left' |
      'border-none' |
      'border-outside' |
      'border-right' |
      'border-top-bottom' |
      'border-top-left-bottom' |
      'border-top-left-right' |
      'border-top-left' |
      'border-top-right-bottom' |
      'border-top-right' |
      'border-top' |
      'bow-arrow' |
      'bow' |
      'box-light-dashed-down-left' |
      'box-light-dashed-down-right' |
      'box-light-dashed-up-left' |
      'box-light-dashed-up-right' |
      'box-light-double-horizontal' |
      'box-light-double-round-down-left' |
      'box-light-double-round-down-right' |
      'box-light-double-round-up-left' |
      'box-light-double-round-up-right' |
      'box-light-double-vertical' |
      'box-light-down-left-circle' |
      'box-light-down-left' |
      'box-light-down-right-circle' |
      'box-light-down-right' |
      'box-light-horizontal' |
      'box-light-round-down-left' |
      'box-light-round-down-right' |
      'box-light-round-up-left' |
      'box-light-round-up-right' |
      'box-light-up-left-circle' |
      'box-light-up-left' |
      'box-light-up-right-circle' |
      'box-light-up-right' |
      'box-light-vertical' |
      'box-outer-light-all' |
      'box-outer-light-dashed-all' |
      'box-outer-light-dashed-down-left-right' |
      'box-outer-light-dashed-down-left' |
      'box-outer-light-dashed-down-right' |
      'box-outer-light-dashed-down' |
      'box-outer-light-dashed-left-right' |
      'box-outer-light-dashed-left' |
      'box-outer-light-dashed-right' |
      'box-outer-light-dashed-up-down-left' |
      'box-outer-light-dashed-up-down-right' |
      'box-outer-light-dashed-up-down' |
      'box-outer-light-dashed-up-left-right' |
      'box-outer-light-dashed-up-left' |
      'box-outer-light-dashed-up-right' |
      'box-outer-light-dashed-up' |
      'box-outer-light-down-left-right' |
      'box-outer-light-down-left' |
      'box-outer-light-down-right' |
      'box-outer-light-down' |
      'box-outer-light-left-right' |
      'box-outer-light-left' |
      'box-outer-light-right' |
      'box-outer-light-round-down-left' |
      'box-outer-light-round-down-right' |
      'box-outer-light-round-up-left' |
      'box-outer-light-round-up-right' |
      'box-outer-light-up-down-left' |
      'box-outer-light-up-down-right' |
      'box-outer-light-up-down' |
      'box-outer-light-up-left-right' |
      'box-outer-light-up-left' |
      'box-outer-light-up-right' |
      'box-outer-light-up' |
      'box' |
      'briefcase' |
      'bug-fill' |
      'bug' |
      'calculator' |
      'calendar-month' |
      'calendar' |
      'cancel' |
      'card-text' |
      'card' |
      'cart' |
      'chart-bar' |
      'chat' |
      'check' |
      'checkbox-blank' |
      'checkbox-cross' |
      'checkbox-marked' |
      'chevron-down-circle' |
      'chevron-down' |
      'chevron-left-circle' |
      'chevron-left' |
      'chevron-right-circle' |
      'chevron-right' |
      'chevron-up-circle' |
      'chevron-up' |
      'circle' |
      'clipboard' |
      'clock' |
      'coffee' |
      'comment-text' |
      'comment' |
      'compass-east-arrow' |
      'compass-north-arrow' |
      'compass-north-east' |
      'compass-north-west' |
      'compass-south-arrow' |
      'compass-south-east' |
      'compass-south-west' |
      'compass-west-arrow' |
      'compass' |
      'credit-card' |
      'crown' |
      'cube-unfolded' |
      'database' |
      'device' |
      'diamond' |
      'division' |
      'door-box' |
      'door-open' |
      'door' |
      'download' |
      'email' |
      'file' |
      'fire' |
      'flask-empty' |
      'flask-round-bottom-empty' |
      'flask-round-bottom' |
      'flask' |
      'floppy-disk' |
      'folder-open' |
      'folder' |
      'gamepad-center' |
      'gamepad-down-left' |
      'gamepad-down-right' |
      'gamepad-down' |
      'gamepad-empty' |
      'gamepad-left' |
      'gamepad-right' |
      'gamepad-up-left' |
      'gamepad-up-right' |
      'gamepad-up' |
      'heart' |
      'image' |
      'label-variant' |
      'label' |
      'led' |
      'lightbulb' |
      'lock-open' |
      'lock' |
      'login' |
      'logout' |
      'map' |
      'menu-bottom-left' |
      'menu-bottom-right' |
      'menu-down-fill' |
      'menu-down' |
      'menu-left-fill' |
      'menu-left-right' |
      'menu-left' |
      'menu-right-fill' |
      'menu-right' |
      'menu-top-left' |
      'menu-top-right' |
      'menu-up-down' |
      'menu-up-fill' |
      'menu-up' |
      'message-processing' |
      'message-text' |
      'message' |
      'microphone' |
      'minus-box-fill' |
      'minus-box' |
      'minus-circle-fill' |
      'minus-circle' |
      'minus' |
      'monitor-image' |
      'monitor' |
      'multiply' |
      'music-note' |
      'necklace' |
      'note' |
      'notebook' |
      'notification' |
      'octagon-alert' |
      'octagon' |
      'pause' |
      'pencil' |
      'pickaxe' |
      'pictogrammers' |
      'pixel.sh' |
      'play' |
      'plus-box-fill' |
      'plus-box' |
      'plus-circle-fill' |
      'plus-circle' |
      'plus' |
      'radiobox-marked' |
      'radiobox' |
      'remove-circle' |
      'rotate-clockwise' |
      'rotate-counterclockwise' |
      'script' |
      'shield' |
      'skull' |
      'speaker' |
      'stop' |
      'sword' |
      'tag-text' |
      'tag' |
      'target' |
      'terminal' |
      'text-box' |
      'text-image' |
      'toggle-switch-off' |
      'toggle-switch-on' |
      'toolbox' |
      'tooltip-above-alert' |
      'tooltip-above-text' |
      'tooltip-above' |
      'tooltip-below-alert' |
      'tooltip-below-text' |
      'tooltip-below' |
      'tooltip-end-alert' |
      'tooltip-end-text' |
      'tooltip-end' |
      'tooltip-start-alert' |
      'tooltip-start-text' |
      'tooltip-start' |
      'trash' |
      'upload' |
      'volume-high' |
      'volume-low' |
      'volume-medium' |
      'volume-mute' |
      'wall-fill' |
      'wall' |
      'water' |
      'well';

    type backgroundType = 'circle' | 'rect' | 'button';

    type positionType = 'top' | 'bottom' | 'right' | 'left' |
      'top_right' | 'top_left' | 'bottom_right' | 'bottom_left';

    type backgroundTypeObj = {
      type?: backgroundType;
      color?: string;
      radius?: number;
      borderRadius?: number;
    };

    type badgeTypeObj = {
      value?: number | string;
      fontSize?: string;
      position?: positionType;
      color?: string;
      backgroundColor?: string;
      radius?: number;
    };

    interface IconProps {
      name: iconNames;
      width?: number;
      height?: number;
      color?: string;
      stroke?: number;
      background?: backgroundType | backgroundTypeObj;
      badge?: number | string | badgeTypeObj;
    }

    const Icon: (props: IconProps & SvgProps & AdditionalProps) => ReactNode;

    export { iconNames };
    export default Icon;
}
